import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder } from 'discord.js';
import { BOUNTY_POINT_EMOJI, BOUNTY_YAO_EMOJI } from './cultivationBounty.js';
const PINK=0xF4A7C5;
const FIGHT='<a:ttgiaochien:1547482030747680898>', CULT='<a:tttuvi:1547448737377427550>', STONES='<a:ttlinhthach:1547448522125869126>', STAMINA='<a:tttheluc:1547448708537262090>', NEXT='<a:tttrang:1547448866440347739>';
const n=v=>new Intl.NumberFormat('vi-VN').format(Math.max(0,Math.round(Number(v)||0)));
function duration(ms){const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return h+' giờ '+m+' phút';}
export function getBountyDashboardButton(ownerId){return new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':bounty').setLabel('Truy Nã').setEmoji({id:'1547682200961556510',name:'ttnhiemvu',animated:true}).setStyle(ButtonStyle.Secondary);}
export function buildBountyEmbed(user,board){
 const lines=[BOUNTY_POINT_EMOJI+' **TRUY NÃ LỆNH**','','“Yêu thú tác loạn, họa loạn Tiên Lộ.','Truy nã lệnh đã ban — chư vị đạo hữu, lĩnh mệnh trảm yêu!”','','━━━━━━━━━━━━━━━━━━━━━━','',BOUNTY_POINT_EMOJI+' **Truy Nã Điểm**\n└ '+n(board.points)+' điểm','',FIGHT+' **Mục tiêu hiện tại**\n└ '+board.targets.filter(t=>!t.completed).length+' / 3 Truy Nã Lệnh','','━━━━━━━━━━━━━━━━━━━━━━'];
 board.targets.forEach((t,i)=>{lines.push('',(['Ⅰ','Ⅱ','Ⅲ'][i])+' · '+BOUNTY_YAO_EMOJI+' 「 '+t.name+' 」','');lines.push(t.stars>=4?'<a:ttdungnham:1547489239682383902> **'+(t.stars===5?'TRUY NÃ HIẾM · ':'')+'★'.repeat(t.stars)+'**':'Cấp truy nã: **'+'★'.repeat(t.stars)+'**');lines.push('Cảnh giới: **'+t.realm+'**','Nguy hiểm: **'+t.danger+'**','',t.completed?'✅ **ĐÃ HOÀN THÀNH**':CULT+' Tu Vi: +'+n(t.reward.cultivation)+'\n'+STONES+' Linh Thạch: +'+n(t.reward.stones)+'\n'+BOUNTY_POINT_EMOJI+' Truy Nã Điểm: +'+n(t.reward.points));if(!t.completed&&t.stars>=3)lines.push('🎁 Có khả năng rơi vật phẩm hiếm');if(i<2)lines.push('','━━━━━━━━━━━━━━━━━━━━━━');});
 lines.push('','━━━━━━━━━━━━━━━━━━━━━━','',NEXT+' Truy Nã Lệnh làm mới\n**Còn '+duration(board.resetRemaining)+'**','','「斬妖除魔 · 懸賞天下」','*Trảm yêu trừ ma — lĩnh thưởng mà về.*');
 return new EmbedBuilder().setColor(PINK).setTitle('𝓣𝓻𝓾𝔂 𝓝𝓪̃ 𝓨𝓮̂𝓾 𝓣𝓱𝓾́ · 妖獸懸賞').setDescription(lines.join('\n'));
}
export function buildBountyRows(ownerId,board){const row=new ActionRowBuilder();board.targets.forEach((t,i)=>row.addComponents(new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':bounty_target:'+i).setLabel(['Ⅰ','Ⅱ','Ⅲ'][i]).setEmoji({id:'1547477368820469780',name:'ttyeuthu',animated:true}).setStyle(ButtonStyle.Secondary).setDisabled(Boolean(t.completed))));row.addComponents(new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':dashboard').setLabel('Quay lại Tiên Lộ').setStyle(ButtonStyle.Secondary));return[row];}
export function buildBountyTargetEmbed(user,result){const t=result.target;return new EmbedBuilder().setColor(PINK).setTitle('𝓣𝓻𝓾𝔂 𝓝𝓪̃ · 追殺令').setDescription([BOUNTY_YAO_EMOJI+' 「 '+t.name+' 」','',BOUNTY_YAO_EMOJI+' Yêu thú\n└ '+t.realm,'<a:ttdaohuu:1547296747301376130> Đạo hữu\n└ <@'+user.id+'>',FIGHT+' Đánh giá\n└ **'+t.danger+'**',STAMINA+' Thể Lực tiêu hao\n└ '+t.staminaCost,'','━━━━━━━━━━━━━━━━━━━━━━','',FIGHT+' Thắng\n└ Nhận toàn bộ phần thưởng Truy Nã.','','Thất bại\n└ Không nhận thưởng · mục tiêu vẫn còn.'].join('\n'));}
export function buildBountyTargetRows(ownerId,t){return[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':bounty_fight:'+t.slot).setLabel('Giao Chiến').setEmoji({id:'1547482030747680898',name:'ttgiaochien',animated:true}).setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':bounty').setLabel('Quay lại Truy Nã').setStyle(ButtonStyle.Secondary))];}
export function buildBountyResultEmbed(result){const t=result.target;if(!result.ok)return new EmbedBuilder().setColor(PINK).setTitle('Truy Nã Yêu Thú').setDescription(result.reason==='stamina'?STAMINA+' **Thể Lực không đủ.**':'Truy Nã Lệnh này không còn khả dụng.');if(!result.success)return new EmbedBuilder().setColor(PINK).setTitle('TRUY NÃ THẤT BẠI').setDescription([BOUNTY_YAO_EMOJI+' 「 '+t.name+' 」 vẫn chưa bị tru sát.','',STAMINA+' Thể Lực đã tiêu hao: **'+t.staminaCost+'**','','Mục tiêu vẫn còn trên Truy Nã Lệnh.'].join('\n'));const loot=result.drop?result.drop.item.name+' ×'+result.drop.quantity:'Không có';return new EmbedBuilder().setColor(PINK).setTitle('TRUY NÃ HOÀN THÀNH').setDescription(['Một kiếm đoạn yêu khí —',BOUNTY_YAO_EMOJI+' 「 '+t.name+' 」 đã bị tru sát!','','━━━━━━━━━━━━━━━━━━━━━━','',CULT+' Tu Vi nhận được\n└ +'+n(result.reward.cultivation),'',STONES+' Linh Thạch\n└ +'+n(result.reward.stones),'',BOUNTY_POINT_EMOJI+' Truy Nã Điểm\n└ +'+n(result.reward.points),'','🎁 Chiến lợi phẩm\n└ '+loot,'','━━━━━━━━━━━━━━━━━━━━━━','',BOUNTY_POINT_EMOJI+' Truy Nã Điểm hiện tại\n└ **'+n(result.points)+' điểm**'].join('\n'));}
export function buildBountyResultRows(ownerId){return[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':bounty').setLabel('Quay lại Truy Nã').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':dashboard').setLabel('Tiên Lộ').setStyle(ButtonStyle.Secondary))];}
