import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder } from 'discord.js';
import { BOUNTY_POINT_EMOJI, BOUNTY_YAO_EMOJI } from './cultivationBounty.js';
const PINK=0xF4A7C5;
const FIGHT='<a:ttgiaochien:1547482030747680898>', CULT='<a:tttuvi:1547448737377427550>', STONES='<a:ttlinhthach:1547448522125869126>', STAMINA='<a:tttheluc:1547448708537262090>', NEXT='<a:tttrang:1547448866440347739>', USER='<:ttdaohuu:1547296747301376130>', CHEST='<a:ttruongco:1547493008914653245>', TITLE_L='<a:trangtrig2:1546040703375904801>', TITLE_R='<a:trangtrig3:1546040818261954610>';
const n=v=>new Intl.NumberFormat('vi-VN').format(Math.max(0,Math.round(Number(v)||0)));
function duration(ms){const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return h+' giờ '+m+' phút';}
export function getBountyDashboardButton(ownerId){return new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':bounty').setLabel('Truy Nã').setEmoji({id:'1547682200961556510',name:'ttnhiemvu',animated:true}).setStyle(ButtonStyle.Secondary);}
export function buildBountyEmbed(user,board){
 const lines=[BOUNTY_POINT_EMOJI+' **TRUY NÃ LỆNH**','','“Yêu thú tác loạn, họa loạn Tiên Lộ.','Truy nã lệnh đã ban — chư vị đạo hữu, lĩnh mệnh trảm yêu!”','','━━━━━━━━━━━━━━━━━━━━━━','',BOUNTY_POINT_EMOJI+' **Truy Nã Điểm:** '+n(board.points)+' điểm','',FIGHT+' **Mục tiêu hiện tại:** '+board.targets.filter(t=>!t.completed).length+' / 3 Truy Nã Lệnh','','━━━━━━━━━━━━━━━━━━━━━━'];
 board.targets.forEach((t,i)=>{lines.push('',(['Ⅰ','Ⅱ','Ⅲ'][i])+' · '+BOUNTY_YAO_EMOJI+' 「 '+t.name+' 」','');lines.push(t.stars>=4?'<a:ttdungnham:1547489239682383902> **'+(t.stars===5?'TRUY NÃ HIẾM · ':'')+'★'.repeat(t.stars)+'**':'Cấp truy nã: **'+'★'.repeat(t.stars)+'**');lines.push('Cảnh giới: **'+t.realm+'**','Nguy hiểm: **'+t.danger+'**','',t.completed?'✅ **ĐÃ HOÀN THÀNH**':CULT+' Tu Vi: +'+n(t.reward.cultivation)+'\n'+STONES+' Linh Thạch: +'+n(t.reward.stones)+'\n'+BOUNTY_POINT_EMOJI+' Truy Nã Điểm: +'+n(t.reward.points));if(!t.completed&&t.stars>=3)lines.push(CHEST+' Có khả năng rơi vật phẩm hiếm');if(i<2)lines.push('','━━━━━━━━━━━━━━━━━━━━━━');});
 lines.push('','━━━━━━━━━━━━━━━━━━━━━━','',NEXT+' **Truy Nã Lệnh làm mới:** Còn '+duration(board.resetRemaining),'','「斬妖除魔 · 懸賞天下」','*Trảm yêu trừ ma — lĩnh thưởng mà về.*');
 return new EmbedBuilder().setColor(PINK).setTitle(TITLE_L+' 𝓣𝓻𝓾𝔂 𝓝𝓪̃ 𝓨𝓮̂𝓾 𝓣𝓱𝓾́ · 妖獸懸賞 '+TITLE_R).setDescription(lines.join('\n'));
}
export function buildBountyRows(ownerId,board){const row=new ActionRowBuilder();board.targets.forEach((t,i)=>row.addComponents(new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':bounty_target:'+i+'~'+board.date).setLabel(['Ⅰ','Ⅱ','Ⅲ'][i]).setEmoji({id:'1547477368820469780',name:'ttyeuthu',animated:true}).setStyle(ButtonStyle.Secondary).setDisabled(Boolean(t.completed))));row.addComponents(new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':dashboard').setLabel('Quay lại Tiên Lộ').setStyle(ButtonStyle.Secondary));return[row];}
export function buildBountyTargetEmbed(user,result){const t=result.target;return new EmbedBuilder().setColor(PINK).setTitle(TITLE_L+' 𝓣𝓻𝓾𝔂 𝓝𝓪̃ · 追殺令 '+TITLE_R).setDescription([BOUNTY_YAO_EMOJI+' 「 '+t.name+' 」','',BOUNTY_YAO_EMOJI+' **Yêu thú:** '+t.realm,USER+' **Đạo hữu:** <@'+user.id+'>',FIGHT+' **Đánh giá:** '+t.danger,STAMINA+' **Thể Lực tiêu hao:** '+(t.actualStaminaCost ?? t.staminaCost),'','━━━━━━━━━━━━━━━━━━━━━━','',FIGHT+' **Thắng:** Nhận toàn bộ phần thưởng Truy Nã.','**Thất bại:** Không nhận thưởng · mục tiêu vẫn còn.'].join('\n'));}
export function buildBountyTargetRows(ownerId,t,boardDate){return[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':bounty_fight:'+t.slot+'~'+boardDate).setLabel('Giao Chiến').setEmoji({id:'1547482030747680898',name:'ttgiaochien',animated:true}).setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':bounty').setLabel('Quay lại Truy Nã').setStyle(ButtonStyle.Secondary))];}
export function buildBountyResultEmbed(result){const t=result.target;if(!result.ok){let message='Truy Nã Lệnh này không còn khả dụng.';if(result.reason==='stamina')message=STAMINA+' **Thể Lực không đủ để giao chiến.**';if(result.reason==='completed')message='✅ **Truy Nã Lệnh này đã hoàn thành.**';if(result.reason==='expired_board')message=NEXT+' **Truy Nã Lệnh cũ đã hết hạn. Hãy mở danh sách mới.**';return new EmbedBuilder().setColor(PINK).setTitle('Truy Nã Yêu Thú').setDescription(message);}if(!result.success)return new EmbedBuilder().setColor(PINK).setTitle(TITLE_L+' TRUY NÃ THẤT BẠI '+TITLE_R).setDescription([BOUNTY_YAO_EMOJI+' 「 '+t.name+' 」 vẫn chưa bị tru sát.','',STAMINA+' **Thể Lực đã tiêu hao:** '+(t.actualStaminaCost ?? t.staminaCost),'','Mục tiêu vẫn còn trên Truy Nã Lệnh.'].join('\n'));const loot=result.drop?result.drop.item.name+' ×'+result.drop.quantity:'Không có';return new EmbedBuilder().setColor(PINK).setTitle(TITLE_L+' TRUY NÃ HOÀN THÀNH '+TITLE_R).setDescription(['Một kiếm đoạn yêu khí —',BOUNTY_YAO_EMOJI+' 「 '+t.name+' 」 đã bị tru sát!','','━━━━━━━━━━━━━━━━━━━━━━','',CULT+' **Tu Vi nhận được:** +'+n(result.reward.cultivation),'',STONES+' **Linh Thạch:** +'+n(result.reward.stones),'',BOUNTY_POINT_EMOJI+' **Truy Nã Điểm:** +'+n(result.reward.points),'',CHEST+' **Chiến lợi phẩm:** '+loot,'','━━━━━━━━━━━━━━━━━━━━━━','',BOUNTY_POINT_EMOJI+' **Truy Nã Điểm hiện tại:** '+n(result.points)+' điểm'].join('\n'));}
export function buildBountyResultRows(ownerId){return[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':bounty').setLabel('Quay lại Truy Nã').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('tutien_action:'+ownerId+':dashboard').setLabel('Tiên Lộ').setStyle(ButtonStyle.Secondary))];}
